version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/hirsch88/go-trophy-server
    steps:
      - checkout
      - run: cp .env.example .env
      - run: make install
      - run: make mock
      - run: make test
